// Copy the pure, browser-safe shared modules into extension/vendor/ so the
// extension (which cannot import Node modules) uses the exact same detection
// engine and protocol definitions as the server. Keeps one source of truth.
//
// Run: npm run sync:shared

import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, '..');

// Only modules with zero Node dependencies are safe to vendor into the browser.
const MODULES = ['matcher.js', 'protocol.js', 'config.js'];

const BANNER =
  '// AUTO-GENERATED by scripts/sync-shared.js — do not edit here.\n' +
  '// Edit shared/<file> and run `npm run sync:shared`.\n';

async function main() {
  const outDir = join(root, 'extension/vendor');
  await mkdir(outDir, { recursive: true });
  for (const mod of MODULES) {
    const src = await readFile(join(root, 'shared', mod), 'utf8');
    if (/from '\s*node:/.test(src) || /require\(/.test(src)) {
      throw new Error(`Refusing to vendor ${mod}: it references Node built-ins.`);
    }
    await writeFile(join(outDir, mod), BANNER + src);
    console.log(`vendored shared/${mod} -> extension/vendor/${mod}`);
  }
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
